name: ci-wf
on: 
  push: 
    branches:
      - develop
  pull_request:
    branches:
      - develop  
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Repository Information
        run: |
          echo "Repository Name: ${{github.repository}}"
          echo "Type of Event: ${{github.event_name}}"
          git -v
          git log 
          git branch
          git branch feature/home-page
          git switch feature/home-page
          mkdir ./css
          touch home-page.html ./css/home-page.css
          git status
          git config --local user.name "Arslan Fakhir"
          git config --local user.email l1f21bsse0493@ucp.edu.pk
          git add .
          git commit -m "add home-page.html and home-page.css"
          git status
